---
- name: Install Grafana
  hosts: main 
  become: yes

  vars:
    new_hostname: "Grafana server"

  tasks:
    - name: Set the hostname
      hostname:
        name: "{{ new_hostname }}"

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - software-properties-common
          - wget
        state: present
        update_cache: yes

    - name: Add Grafana GPG key
      apt_key:
        url: "https://packages.grafana.com/gpg.key"
        state: present

    - name: Add Grafana APT repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present
        filename: grafana

    - name: Update and install Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Start Grafana server
      systemd:
        name: grafana-server
        state: started
        enabled: yes