---
- name: Install Jenkins
  hosts: jenkins
  become: yes

  vars:
    - ansible_ssh_common_args: '-o IdentitiesOnly=yes'
  
  tasks:
    - name: Download keyring
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
    - name: Ensure repo added to source list
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]  https://pkg.jenkins.io/debian-stable binary/
        state: present
        filename: jenkins
    - name: Ensure ca-certificates is up-to-date
      ansible.builtin.apt:
        name: ca-certificates
        state: latest
        update_cache: yes
    - name: Install java
      apt:
        name:
          - fontconfig
          - openjdk-17-jre
        update_cache: true
    - name: Install Jenkins
      apt:
        name: jenkins
        update_cache: true
    - name: Start Jenkins service
      systemd_service:
        name: jenkins
        enabled: true
        state: started
        
